### ISSUE TITLE
Page for credits/contact-info/about-us

### ISSUE THREAD

**Issue by nmp14** [BudgeGrub/Budgegrub#23]
In the footer, we want to be able to redirect users to an about us page that gives a quick description of the group.

We should include basic info like github repos. Can add more if desired. 

This should preferably be handled with a new html page and its own styling. Styling should be kept simple and focused on content more than fancy colors.

**Comment by MikeGordillo** [comment]
A hyper link has been added in the footer that redirects user to group members, social media, gitHub and other contacts. The contact page is a separate html file. Kept the same styling as the App to make it cohesive.
